[theme]
base="dark"
primaryColor="#1f77b4"
backgroundColor="#0e1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"


[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
favicon = "techxos_favicon.ico"
